<?php
 function fetch_data()
 {
session_start();
      $output = '';
      $con=mysqli_connect('localhost','root','','agromart');
      $uname = $_SESSION['user'];
      $total=0;
      $sql = "SELECT * FROM cart WHERE username = '$uname'";
      $rt=mysqli_query($con, $sql);
      if(mysqli_num_rows($rt)>0){
       while($kk = mysqli_fetch_assoc($rt)){
         $id = $kk['proid'];
         $qty=$kk['qty'];
         $sql = "SELECT * FROM product WHERE product_id =$id";
         $results=mysqli_query($con, $sql);
         while($jk = mysqli_fetch_assoc($results)){
           $amount=$jk["price"]*$kk["qty"];
           $total=$total+$amount;
      {
      $output .= '<tr>
                          <td>'.$jk["name"].'</td>
                          <td>'.$kk["qty"].'</td>
                          <td align="right">'.$jk["price"].'</td>
                            <td>'.$amount.'</td>
                     </tr>
                          ';
      }}
    }





         $output .= '<tr><td colspan="4"></td></tr>
         <tr><td></td><td></td>
                          <td><B>GRAND TOTAL</B>:</td>
                             <td><B>'.$total.'</B></td>
                                                   </tr>
                             ';


      return $output;
 }}
 if(isset($_GET["create_pdf"]))
 {
      require_once('tcpdf/tcpdf.php');
      $obj_pdf = new TCPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
      $obj_pdf->SetCreator(PDF_CREATOR);
      $obj_pdf->SetTitle("Bill");
      $obj_pdf->SetHeaderData('', '', PDF_HEADER_TITLE, PDF_HEADER_STRING);
      $obj_pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
      $obj_pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
      $obj_pdf->SetDefaultMonospacedFont('helvetica');
      $obj_pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
      $obj_pdf->SetMargins(PDF_MARGIN_LEFT, '5', PDF_MARGIN_RIGHT);
      $obj_pdf->setPrintHeader(false);
      $obj_pdf->setPrintFooter(false);
      $obj_pdf->SetAutoPageBreak(TRUE, 10);
      $obj_pdf->SetFont('helvetica', '', 12);
      $obj_pdf->AddPage();
      $content = '';
      $content .= '
      <h3 align="center"><BR>
Tax Invoice<br>
<hr>
      <p style="font-size:30px;">Agro-MART</p>
      Next Muttha Chamber<br>
      Senapati Bapat Road, Pune, Maharashtra, 411016<br>
Tel:9809876567 , 5678909876<BR>Email:Agromart2022@gmail.com<BR><BR><BR></h3>

      <table border="1" cellspacing="0" cellpadding="5">
           <tr>
                <th width="35%"><b>NAME</b></th>
                <th width="15%"><b>QTY</b></th>
                <th width="25%" align="right"><b>PRIZE</b></th>
                <th width="25%"><b>SUM AMOUNT</b></th>

           </tr>
      ';
      $content .= fetch_data();
      $content .= '</table><BR>

      <p style="font-size:7px;">AUTOGENERATED BY COMPUTER</P>';
      $obj_pdf->writeHTML($content);
      $obj_pdf->Output('bill.pdf', 'I');
 }
 ?>
 <?php session_start();?>
 <?php

 $con=mysqli_connect('localhost','root','','agromart');
 $uname = $_SESSION['user'];
 $count = 0;
 $id = 0;
 $total=0;
 $sql = "SELECT * FROM cart WHERE username = '$uname' order by cid desc" or die (mysqli_error($con));
 $result=mysqli_query($con, $sql) or die (mysqli_error($con));
 if(mysqli_num_rows($result)>=0){
 while($row = mysqli_fetch_assoc($result)){
   $id = $row['proid'];
   $qty = $row['qty'];
   $count++;
   $sql = "SELECT * FROM product WHERE product_id = $id " or die (mysqli_error($con));
   $r=mysqli_query($con, $sql) or die (mysqli_error($con));
   if(mysqli_num_rows($result)>=0){
       $row = mysqli_fetch_assoc($r);
       $id = $row['product_id'];
       $total=$total+($qty*$row['price']);
     }
   }
 }
 $uid = $_SESSION['uid'];


 $sql1=" select * from  `user` where user_id='$uid'";
 $result=mysqli_query($con,$sql1);
 $row=mysqli_fetch_assoc($result);


 ?>



 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
 </head>
 <body>
 <section style="background-color: #eee;">
   <div class="container py-5">
     <div class="row d-flex justify-content-center">
       <div class="col-md-8 col-lg-6 col-xl-4">
         <div class="card rounded-3">
           <div class="card-body mx-1 my-2">
             <div class="d-flex align-items-center">
               <div>
                 <i class="fab fa-cc-visa fa-4x text-black pe-3"></i>
               </div>
               <div>
                 <p class="d-flex flex-column mb-0">
                   <b> <?php echo $row['fname'] ?></b><span class="small text-muted"></span>
                 </p>
               </div>
             </div>

             <div class="pt-3">
               <div class="d-flex flex-row pb-3">
                 <div class="rounded border border-primary border-2 d-flex w-100 p-3 align-items-center"
                   style="background-color: rgba(18, 101, 241, 0.07);">
                   <div class="d-flex align-items-center pe-3">

                   </div>
                   <div class="d-flex flex-column">
                     <p class="mb-1 small text-primary">Total amount </p>
                     <h6 class="mb-0 text-primary"><?php echo $total ?></h6>
                   </div>
                 </div>
               </div>

               <div class="d-flex flex-row pb-3">
                 <div class="rounded border d-flex w-100 px-3 py-2 align-items-center">
                   <div class="d-flex align-items-center pe-3">

                 </div>
                   <div class="d-flex flex-column py-1">

                     <div class="d-flex flex-row align-items-center">
                       <h6 class="mb-0 text-primary pe-1">Password</h6>
                       <form method="post">
                       <input type="password" class="form-control form-control-sm" id="numberExampler" name="password"
                         style="width: 150px;" />&nbsp;&nbsp;&nbsp;<br>
                         <input type="submit" value="check" class="btn btn-primary" id="check"name="check">
                         </form>
                     </div>
                   </div>
                 </div>
               </div>
             </div>
             <?php
               if(isset($_POST["check"])){
                 $pswd=md5($_POST['password']);
                 $uname = $_SESSION['user'];
                 $sql="SELECT * FROM login where username='$uname' AND password='$pswd'";
                 $result=mysqli_query($con, $sql) or die (mysqli_error($con));
                 if(mysqli_num_rows($result)>0){
             ?>
               <div class="d-flex justify-content-between align-items-center pb-1">
               <a href="customer.php" class="text-muted">Go back</a>
               <form action="billprocess.php" method="get">
               <input type="submit" name="submit" value="Pay amount" class="btn btn-primary btn-lg">
             </form>
             <form action="" method="GET">
                 <button type="submit" class="btn btn-success  wow fadeInDown" name="create_pdf"  type="submit"value="" /> BILL</button>
             </form>

           <?php
             }
             else{
                 echo '<script>alert("Enter the correct password to continue!!");</script>';
             }
           }?>

             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>
 </body>

 </html>
